variables:
  CI_DEBUG_TRACE: "false"

stages:
    - build
    - dbseed
    - test
    - deploy
    - production

build-php:
    stage: build
    only:
        - master
    script:
        - cp /home/gitlab-runner/.env.dev.panor.ru ./.env
        - php72 /usr/bin/composer install
        - php72 ./artisan cache:clear
        - php72 ./artisan config:clear
    artifacts:
        name: "$CI_BUILD_REF_NAME-$CI_COMMIT_REF_NAME_php"
        untracked: true
        paths:
            - .env
            - composer.lock
            - bootstrap/
            - vendor/

build-npm:
    stage: build
    only:
        - master
    script:
        - npm update
        - npm install
        - npm run prod
    artifacts:
        name: "$CI_BUILD_REF_NAME-$CI_COMMIT_REF_NAME_npm"
        untracked: true
        paths:
            - package-lock.json
            - public/
            - node_modules/

dbseed:
    stage: dbseed
    only:
        - master
    script:
        - echo $MYSQL_PASS
        - mysql --user=$MYSQL_USER --password=$MYSQL_PASS -e "drop database if exists dev_panor; create database dev_panor;" dev_panor
        - php72 ./artisan migrate:fresh -vvv
        - php72 ./artisan db:seed --class=TestSeeder -vvv
        - php72 ./artisan admin:create
    dependencies:
        - build-php
        - build-npm

test:
    stage: test
    only:
        - master
    script:
        # - php72 ./vendor/phpunit/phpunit/phpunit --testdox --coverage-text --colors=never tests
        - php72 ./artisan cache:clear
        - php72 ./artisan config:clear
        - php72 ./artisan route:clear
        - php72 ./artisan view:clear
        - php72 /usr/bin/composer dumpautoload
        - php72 ./vendor/brianium/paratest/bin/paratest -p4 --coverage-text tests
    dependencies:
        - build-php
        - build-npm
        - dbseed

deploy:
    stage: deploy
    only:
        - master
    script:
        - sftp -i /home/gitlab-runner/.ssh/id_rsa gitlab-runner@jurdev.panor.ru <<< 'put -r ../laravel-panor /var/www/html/dev.panor.ru.new'
        - ssh -i /home/gitlab-runner/.ssh/id_rsa gitlab-runner@jurdev.panor.ru 'cd /var/www/html/dev.panor.ru.new && php72 ./artisan migrate:fresh && php72 ./artisan db:seed --class=TestSeeder && php72 ./artisan admin:create'
        - ssh -i /home/gitlab-runner/.ssh/id_rsa gitlab-runner@jurdev.panor.ru 'cd /var/www/html/dev.panor.ru.new && chmod 774 ./deploy && ./deploy'
    dependencies:
        - build-php
        - dbseed
        - test

# Задача на развертывание PRODUCTION релиза
# Обычно проускается
# Выполгяется в ручном режиме по мере необходимости
# production:
#     stage: production
#     script:
#         - echo "Deploy to PRODUCTION..."
#         - /usr/local/bin/prod-dev.panor.ru $USER $PASS dev.panor.ru
#     only:
#         - master
#     when: manual
