stages:
    - deploy
    # - production

deploy:
    stage: deploy
    script:
        - php72 /usr/bin/composer install
        - npm install
        - npm run prod
        - cp /usr/local/bin/.env.dev.panor.ru ./.env
        - mysql --user=$MYSQL_USER --password=$MYSQL_PASS -e "drop database if exists dev_panor; create database dev_panor;" dev_panor
        - php72 ./artisan migrate -vvv
        - php72 ./artisan db:seed -vvv
        - php72 ./artisan db:seed --class=TestSeeder -vvv
        - php72 ./artisan cache:clear
        - php72 ./artisan config:cache
        - /usr/bin/phpunit --testdox tests
        - chmod 774 ./deploy
        - ./deploy
    only:
        - master

# Задача на развертывание PRODUCTION релиза
# Обычно проускается
# Выполгяется в ручном режиме по мере необходимости
# production:
#     stage: production
#     script:
#         - echo "Deploy to PRODUCTION..."
#         - /usr/local/bin/prod-dev.panor.ru $USER $PASS dev.panor.ru
#     only:
#         - master
#     when: manual
