stages:
    - build
    - dbseed
    - test
    - deploy
    # - production

cache:
    key: ${CI_JOB_NAME}
    paths:
        - .env
        - composer.lock
        - package-lock.json
        - bootstrap/
        - node_modules/
        - public/
        - vendor/

build:
    stage: build
    script:
        - php72 /usr/bin/composer install
        - npm update
        - npm install
        - npm run prod
        - cp /usr/local/bin/.env.dev.panor.ru ./.env
        - php72 ./artisan cache:clear
        - php72 ./artisan config:cache
    only:
        - master

dbseed:
    stage: dbseed
    script:
        - mysql --user=$MYSQL_USER --password=$MYSQL_PASS -e "drop database if exists dev_panor; create database dev_panor;" dev_panor
        - php72 ./artisan migrate -vvv
        - php72 ./artisan db:seed --class=TestSeeder -vvv
    only:
        - master

test:
    stage: test
    script:
        - php72 /usr/bin/phpunit --testdox tests
    only:
        - master

deploy:
    stage: deploy
    script:
        - chmod 774 ./deploy
        - ./deploy
    only:
        - master

# Задача на развертывание PRODUCTION релиза
# Обычно проускается
# Выполгяется в ручном режиме по мере необходимости
# production:
#     stage: production
#     script:
#         - echo "Deploy to PRODUCTION..."
#         - /usr/local/bin/prod-dev.panor.ru $USER $PASS dev.panor.ru
#     only:
#         - master
#     when: manual
