stages:
    - phpunit_tests
    # - qunit_tests
    - build
    - deploy
    # - production

phpunit_tests:
    stage: phpunit_tests
    script:
        - /usr/bin/phpunit --testdox tests
    only:
        - master

# qunit_tests:
#     stage: qunit_tests
#     script:
#         - /usr/bin/qunit testjs
#     only:
#         - master

build:
    stage: build
    script:
        - /usr/local/bin/build-dev.panor.ru $USER $PASS dev.panor.ru.build
    only:
        - master

deploy:
    stage: deploy
    variables:
        CI_DEBUG_TRACE: "false"
    script:
        # - /usr/local/bin/deploy-dev.panor.ru $USER $PASS dev.panor.ru
        - /usr/local/bin/deploy-dev.panor.ru dev.panor.ru
    only:
        - master

# Задача на развертывание PRODUCTION релиза
# Обычно проускается
# Выполгяется в ручном режиме по мере необходимости
# production:
#     stage: production
#     script:
#         - echo "Deploy to PRODUCTION..."
#         - /usr/local/bin/prod-dev.panor.ru $USER $PASS dev.panor.ru
#     only:
#         - master
#     when: manual
