#!/bin/bash

WEB=/var/www/html
PROJECT=$WEB/dev.panor.ru

chown -R gitlab-runner:nginx $PROJECT.new

if [ -d "$PROJECT.prev" ]; then
    rm -rf $PROJECT.prev
fi

if [ -d "$PROJECT" ]; then
    mv $PROJECT $PROJECT.prev
    mv $PROJECT.new $PROJECT
    cd $PROJECT
    npm install
    npm run dev
    php72 ./artisan config:cache
    php72 ./artisan cache:clear
fi
